auth_enabled: false

server:
  http_listen_port: 3100
  log_level: info

common:
  path_prefix: /loki # Prefijo para todos los directorios internos de Loki
  storage:
    filesystem:
      chunks_directory: /loki/chunks
      rules_directory: /loki/rules
  replication_factor: 1
  ring:
    instance_addr: 127.0.0.1
    kvstore:
      store: inmemory

schema_config:
  configs:
    - from: 2020-10-24 # Cambiar esta fecha a una actual si es un setup nuevo o mantenerla si es un estándar que sigues
      store: boltdb-shipper
      object_store: filesystem
      schema: v11 # o v12, v13 dependiendo de la versión de Loki y necesidades
      index:
        prefix: index_
        period: 24h

storage_config:
  boltdb_shipper:
    active_index_directory: /loki/index
    cache_location: /loki/cache
    cache_ttl: 24h
    shared_store: filesystem # Asegurar que coincida con object_store arriba si se usa boltdb-shipper

compactor:
  working_directory: /loki/compactor # Directorio de trabajo (se creará bajo path_prefix)
  compaction_interval: 10m
  retention_enabled: true
  retention_delete_delay: 2h
  retention_delete_worker_count: 150

limits_config:
  reject_old_samples: true
  reject_old_samples_max_age: 168h # 7 días
  # Deshabilita la validación de esquema v13 para metadata estructurada si no la usas o hay problemas.
  # Para versiones recientes de Loki, structured_metadata es el camino a seguir.
  # allow_structured_metadata: false # Comentado, ya que usualmente se quiere permitir por defecto en nuevas versiones.
  # Si tu regex de promtail no extrae metadata estructurada, esta opción tiene menos impacto.

ruler:
  alertmanager_url: http://localhost:9093 # Si usaras Alertmanager con Loki