version: '3.8'

x-common-opts: &common-opts
  restart: unless-stopped
  env_file: [.env]
  environment:
    - TZ
  volumes:
    - /etc/localtime:/etc/localtime:ro
    - /etc/timezone:/etc/timezone:ro
    - /usr/share/zoneinfo:/usr/share/zoneinfo:ro

services:
  loki:
    image: grafana/loki:2.9.7
    container_name: loki
    <<: *common-opts
    ports:
      - "${LOKI_PORT:-3100}:3100"
    command:
      - "-config.expand-env=true"
      - "-config.file=/etc/loki/local-config.yaml"
    volumes:
      - loki_data:${LOKI_STORAGE_PATH:-/loki}
      - ./loki/config.yaml:/etc/loki/local-config.yaml:ro

  promtail:
    image: grafana/promtail:2.9.7
    container_name: promtail
    <<: *common-opts
    depends_on:
      - loki
    command:
      - "-config.expand-env=true"
      - "-config.file=/etc/promtail/promtail.yaml"
    volumes:
      - ./promtail/promtail.yaml:/etc/promtail/promtail.yaml:ro
      - ${FAIL2BAN_LOG_PATH}:${FAIL2BAN_LOG_PATH}:ro
      - promtail_positions:/etc/promtail

  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    container_name: fail2ban-api
    <<: *common-opts
    depends_on:
      - loki
    ports:
      - "${API_PORT:-8000}:8000"
    volumes:
      - /var/run/fail2ban/fail2ban.sock:/var/run/fail2ban/fail2ban.sock
      - ${FAIL2BAN_LOG_PATH}:${FAIL2BAN_LOG_PATH}:ro

volumes:
  loki_data:
  promtail_positions:
